# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/Gene_Regulatory_NW_id',
                'doc_host': 'https://maud73.github.io',
                'git_url': 'https://github.com/maud73/Gene_Regulatory_NW_id',
                'lib_path': 'Gene_Regulatory_NW_id'},
  'syms': {'Gene_Regulatory_NW_id.core': {'Gene_Regulatory_NW_id.core.foo': ('core.html#foo', 'Gene_Regulatory_NW_id/core.py')}}}
